### PR TITLE
Remove babel dependencies

### LINKED ISSUE #43: Remove babel dependencies
As per now, only the tests use `babel`. IMO it's overkill to use `babel` for testing.

### PR DESCRIPTION
**Pull request by mariuslundgard**
Closes #43.

### CODE REVIEW

**Comment by cristobal** [comment]
Do we really need to an node v4 support, in our test phase?

**Comment by cristobal** [comment]
@mariuslundgard ok i see for the travis build  pipeline.

Also i think we should have another look on how we approach the test part.

**Comment by mariuslundgard** [comment]
We can probably remove Node v4 support.

Would be awesome if you could implement a better test suite @cristobal!

**Comment by cristobal** [comment]
@mariuslundgard ok I will merge this PR then and see how we schedule #51 in an upcoming release.

**Pull request merged**
